config/routes.rb
Talks::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "sessions"}

  resources :talks
  resources :users, :only => [:show, :edit]

  match 'contact' => 'pages#contact'
  root :to => 'pages#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  attr_accessible :talk, :title, :url, :token, :author_name, :author_url, :data
  include HTTParty

  SPEAKERDECK_OEMBED_ENDPOINT = "https://speakerdeck.com/oembed.json?url="

  belongs_to :talk
  before_save :get_info

  def get_info
    # change this into a resque event
    request = HTTParty.get(SPEAKERDECK_OEMBED_ENDPOINT + url)
    if request.response.code == "200"
      info_hash = hash_from_speakerdeck_response(JSON.parse(request.body))
      info_hash.each{ |k, v| self.send("#{k}=".to_sym, v) }
    end
  end

  def thumbnail
    "https://speakerd.s3.amazonaws.com/presentations/#{token}/slide_0.jpg"
  end

  def hash_from_speakerdeck_response(info)
    {
      :author_name => info["author_name"],
      :author_url => info["author_url"],
      :title => info["title"],
      :token => info["html"].match(/speakerdeck.com\/player\/([a-zA-Z0-9]+)/)[1],
      :data => info.to_s
    }
  end
end

#preview slide 640x480 - presentations/hash_here/preview_slide_1.jpg
#slide 1024x768 - presentations/hash_here/slide_1.jpg

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :title, :description, :presentation_attributes, :video_attributes, :transitions, :user

  has_one :presentation
  has_one :video
  belongs_to :user

  accepts_nested_attributes_for :video
  accepts_nested_attributes_for :presentation

  def self.initialize_with_nested_models
    Talk.new.tap do |talk|
      talk.build_video
      talk.build_presentation
    end
  end

  def transitions_json
    # Converts string of 1@0:02, 2@0:04, 3@ 0:06, 4@0:10, 5@1:00 to array of hashes
    if transitions
      pairs = transitions.split(",")
      pairs.map do |pair|
        slide, time = pair.split("@")
        { :slide => slide.to_i, :time => ChronicDuration::parse(time) }
      end.to_json
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me, :username
  # attr_accessible :title, :body

  has_many :talks
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :talk, :url, :duration

  belongs_to :talk
  before_save :get_info

  def get_info
    info_hash = YoutubeParser.search(url).first
    info_hash.each{ |k, v| self.send("#{k}=".to_sym, v) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :store_location

  def after_sign_in_path_for(resource)
    return_to = get_return_to(talks_path)
    clear_stored_location
    return_to
  end

private
  def set_full_width
    @full_width = true
  end

  def require_login
    unless current_user
      flash[:error] = "You must be logged in to access that page."
      redirect_to new_user_session_path
    end
  end

  def store_location
    # raise request.inspect
    session[:return_to] = request.fullpath
  end

  def clear_stored_location
    session[:return_to] = nil
  end

  def get_return_to(alternate=nil)
    session[:return_to] || alternate || root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  protect_from_forgery
  before_filter :set_full_width

  def contact
    @people = [
      {
        :name => "Ed Weng",
        :twitter_handle => "wengzilla",
        :profile_photo_url => "ed_profile.jpg",
        :bio => "Ed is a part-time entrepreneur and a full-time hacker. He enjoys long walks on the beach and a strong refactor."
      }, 
      {
        :name => "Ben Dear",
        :twitter_handle => "Ben_Dear",
        :profile_photo_url => "ben_profile.jpg"
      }]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  skip_before_filter :store_location
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update]

  protect_from_forgery

  def index
    @talks = Talk.all
  end

  def show
    @talk = Talk.find(params[:id])
  end

  def new
    @talk = Talk.initialize_with_nested_models
  end

  def create
    if @talk = current_user.create_talk(params[:talk])
      redirect_to talks_path, :success => "Your talk was successfully created!"
    else
      render 'new', :flash => @talk.errors
    end
  end

  def edit
    @talk = current_user.talks.find(params[:id])
  end

  def update
    @talk = current_user.talks.find(params[:id])
    @talk.update_attributes(params[:talk])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  before_filter :set_full_width, :only => [:show]

  def show
    user
  end

  def edit
    user
  end

  def update
    user.update_attributes(params[:user])
  end

  def user
    @user = User.find_by_username(params[:id]) || User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Talks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <!--[if lt IE 8]>
  <%= stylesheet_link_tag "font-awesome-ie7.min.css", media: "all" %>
  <![endif]-->

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
</head>
<body>

  <%= render :partial => "shared/navbar" %>
  <div class="container">
    <%= render :partial => "shared/flashes" %>
    <%= yield unless @full_width %>
  </div>

  <%= yield if @full_width %>
</body>
</html>

app/views/pages/_person.html.erb
<li class='span3'>
  <figure class='thumbnail-figure'>
    <img alt='<%= person[:name] %>' src='<%= asset_path(person[:profile_photo_url]) %>' class='img-polaroid'>
      <figcaption class='thumbnail-title'>
        <h3>
          <span><%= person[:name].upcase %></span>
        </h3>
      </figcaption>
    </img>
  </figure>
  <p>
    <%= person[:bio] %>
  </p>
  <p>
    <a href="http://twitter.com/<%= person[:twitter_handle] %>"><i class="icon-twitter"></i>@<%= person[:twitter_handle] %></a>
  </p>
</li>

app/views/pages/contact.html.erb
<section class='section alt'>
  <div class='container'>
    <div class='page-header'>
      <h1>
        Our Team
        <small>We are a small team of passionate people who love solving problems.</small>
      </h1>
    </div>
    <ul class='thumbnails bordered thumbnail-list'>
      <%= render :partial => "person", :collection => @people %>
    </ul>
  </div>
</section>

app/views/pages/index.html.erb
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.carousel').flexslider();
  });
</script>

<div class="carousel-wrapper">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="carousel">
          <ul class="slides">
            <li>
              <div style="float:left">
                <i class="icon-bar-chart" style="font-size:300px;"></i>
              </div>
              <div style="padding-top:30px;">
                <p>Welcome to TalkShare</p>
                <p>The new way to share your talks.</p>
              </div>
            </li>
            <li>
              Showcase your presentations in a single spot.
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container" style="padding-top:30px;">
  <div class="section_header">
    <h3>Featured Speakers</h3>
  </div>
  <ul class="hover-block">
    <li style="margin-left: 0px;">
      <a href="#">
        <img src="http://24.media.tumblr.com/tumblr_l8vbm28zsp1qzvno4o1_500.jpg" style="width: 225px; height:225px;"></img>
        <div class="hover-content b-orange" style="top: 180px;">
          <h6>Chad Fowler</h6>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="https://secure.gravatar.com/avatar/540cb3b3712ffe045113cb03bab616a2?s=420&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"></img>
        <div class="hover-content b-orange" style="top: 180px;">
          <h6>Evan Phoenix</h6>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="http://2012.frozenrails.eu/images/speakers/jeff-casimir-288-0d9c1534.jpg;"></img>
        <div class="hover-content b-orange" style="top: 180px;">
          <h6>Jeff Casimir</h6>
        </div>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="http://2012.frozenrails.eu/images/speakers/steve-klabnik-288-98022220.jpg"></img>
        <div class="hover-content b-orange" style="top: 180px;">
          <h6>Steve Klabnik</h6>
        </div>
      </a>
    </li>
  </ul>
</div>

<div class="footer">
  <div class="container">
    Talkshare 2013
  </div>
</div>

<style>
  .slides li {
    display:none;
    font-size: 50px;
    font-weight: 300;
    color: white;
    line-height: 60px;
    height: 350px;
  }

  .carousel-wrapper {
    background-color: #1ba1e2;
    padding-top:150px;
  }

  .footer {
    margin-top:50px;
    padding: 25px 0 25px 0;
    text-align: right;
    background-color: #1ba1e2;
    color: white;
  }
</style>

app/views/shared/_flashes.html.erb
<% unless flash.nil? %>
  <% flash.each do |type, message| %>
    <div class="container boxed">
      <div class="alert alert-<%= type %>">
        <a class="corner-close" onclick="$(this).closest('div.alert').hide(); return false;" href="#" style="float: right">hide</a>
        <%= message %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-static-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_path %>">
          <strong>TalkShare</strong>
        </a>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <li><a href="<%= root_path %>">HOME</a></li>
            <li><a href="<%= talks_path %>">TALKS</a></li>
            <li><a href="<%= contact_path %>">CONTACT US</a></li>
            <% if current_user %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn-header" %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => "btn-header" %></li>
              <li><%= link_to "Sign in", new_user_session_path, :class => "btn-header" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_talk_thumbnail.html.erb
<div class="span4 talk-thumbnail">
  <a href="<%= talk_path(talk) %>"><%= image_tag talk.presentation.thumbnail %></a>
  <div class="talk-info">
    <p class="talk-title"><%= link_to talk.title, talk_path(talk) %></p>
    <p class="talk-user"><%= "#{formatted_date(talk.created_at)} posted by"%> <%= link_to talk.user.username, user_path(talk.user.username) %></p>
  </div>
</div>

app/views/talks/index.html.erb
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.carousel').flexslider();
  });
</script>

<div class="carousel-wrapper">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="carousel">
          <ul class="slides">
            <li>
              <div style="float:right">
                <i class="icon-group" style="font-size:300px;"></i>
              </div>
              <div style="padding-top:30px;">
                <p>Coming soon to a conference near you.</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .slides li {
    display:none;
    font-size: 50px;
    font-weight: 300;
    color: white;
    line-height: 60px;
    height: 350px;
  }


  .footer {
    margin-top:50px;
    padding: 25px 0 25px 0;
    text-align: right;
    background-color: #1ba1e2;
    color: white;
  }
</style>

<div class="container" style="padding-top: 10px;">
  <div class="row" style="margin-top:20px;">
    <%= render :partial => "shared/talk_thumbnail", :collection => @talks, :as => "talk" %>
  </div>

  <!-- <%= link_to "Add a new talk", new_talk_path, :class => "btn btn-primary" %> -->
</div>


<style>
  .carousel-wrapper {
    font-size: 50px;
    font-weight: 300;
    color: white;
    line-height: 60px;

    background-color: #3CBA42;
    padding-top:50px;
    margin-left: -100%;
    margin-right: -100%;
  }
</style>

app/views/talks/new.html.erb
<h1>Add a New Talk</h1>
<hr />
<%= form_for @talk, :html => {:class => "form form-horizontal"} do |talk_form| %>
  <div class="control-group">
    <%= talk_form.label :title, :class => "control-label" %>
    <div class="controls">
      <%= talk_form.text_field :title %>
    </div>
  </div>
  <%= talk_form.fields_for :presentation do |presentation_fields| %>
    <div class="control-group">
      <%= presentation_fields.label :url, "Speaker Deck URL", :class => "control-label" %>
      <div class="controls">
        <%= presentation_fields.text_field :url %>
      </div>
    </div>
  <% end %>

  <%= talk_form.fields_for :video do |video_fields| %>
    <div class="control-group">
      <%= video_fields.label :url, "YouTube URL", :class => "control-label" %>
      <div class="controls">
        <%= video_fields.text_field :url %>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= talk_form.label :transitions, :class => "control-label" %>
    <div class="controls">
      <%= talk_form.text_area :transitions, :placeholder => "1@0:02, 2@0:04, 3@ 0:06, 4@0:10, 5@1:00", :size => "50x6" %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= talk_form.submit :value => "Add", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/talks/show.html.erb
<div style="margin: 0 auto; padding-bottom: 30px; overflow: auto;">
  <div id="presentation_wrapper" class="left-col" style="width: 650px; float: left; margin-right: 40px;">
    <script async class="speakerdeck-embed" data-id="<%= @talk.presentation.token %>" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js" ></script>
  </div>
  <div class="right-col">
    <div id="ytplayer">
    </div>
    <div class="presentation-description" style="background: #aaa; width: 400px; float: left;">
      <%= image_tag "ed_square.jpg" %>
      <%= @talk.user.username %>

      <div id="presentation_info" data-transitions="<%= @talk.transitions_json %>"></div>
      <div id="video_info" data-id="<%= @talk.video.external_id %>"></div>
    </div>
  </div>
</div>

<div id="disqus_wrapper" style="margin: 0 auto;">
  <div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'talkin'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>

app/views/users/show.html.erb
<div class="buffer"></div>
<div class="container">
  <div class="row profile">
    <div class="span6 profile">
      <%= image_tag "ed_square.jpg", :width => 200 %>
      <div class="info">
        <p class="name">Ed Weng</p>
        <p class="area">Rails Programmer, Entrepreneur</p>

        <a href="#" class="twitter">
          <span class="icon icon-twitter-sign"></span>
        </a>
        <a href="#" class="linkedin">
          <span class="icon icon-linkedin-sign"></span>
        </a>
        <a href="#" class="github">
          <span class="icon icon-github-sign"></span>
        </a>
      </div>
    </div>
    <div class="span6 bio">
      Occupy ugh reprehenderit aesthetic, dolor odd future consectetur pug bushwick. Pop-up deep v literally, occaecat sriracha echo park stumptown. Whatever nesciunt minim bespoke laborum, kale chips raw denim 3 wolf moon. Tattooed elit post-ironic nesciunt mumblecore blue bottle. Polaroid next level nisi hashtag kogi est. Sunt hashtag small batch, cliche echo park cred selvage banksy. Nostrud consectetur godard aliquip fixie mcsweeney's, wolf do +1 portland.
    </div>
  </div>
</div>

<div class="container">
  <div class="row margin-left-row">
    <div class="span12">
      <h1>Talks</h1>
      <%= render :partial => "shared/talk_thumbnail", :collection => @user.talks, :as => "talk" %>
    </div>
  </div>
</div>